import Link from "next/link";
import { notFound } from "next/navigation";
import { Icon } from "@iconify/react";
import { SAMPLE_ROLES, getSampleRole } from "@/lib/sampleData";
import PlanReadOnlyView from "@/components/plan/PlanReadOnlyView";

// Public sample plan page. Renders pre-curated demo content for a role —
// no live AI call, no signup gate. Designed to be the thing strangers
// land on from a tweet/LinkedIn post and *immediately* see what Arcora
// produces, before deciding whether to sign up.

export const dynamic = "force-static";
export const revalidate = false;

export function generateStaticParams() {
  return SAMPLE_ROLES.map((r) => ({ role: r.slug }));
}

export async function generateMetadata({ params }) {
  const { role } = await params;
  const found = getSampleRole(role);
  if (!found) {
    return { title: "Sample plan not found" };
  }
  const url = `/sample/${found.slug}`;
  return {
    title: found.seoTitle,
    description: found.seoDescription,
    alternates: { canonical: url },
    openGraph: {
      title: found.seoTitle,
      description: found.seoDescription,
      url,
      type: "article",
    },
    twitter: {
      card: "summary_large_image",
      title: found.seoTitle,
      description: found.seoDescription,
    },
  };
}

export default async function SampleRolePage({ params }) {
  const { role } = await params;
  const found = getSampleRole(role);
  if (!found) notFound();

  return (
    <div className="min-h-screen bg-[#F5F2E8] text-[#1C1917]">
      {/* Lightweight nav — no auth required */}
      <header className="border-b border-[#D1CDC7] bg-[#F5F2E8]/95 sticky top-0 z-30 backdrop-blur">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <Link
            href="/"
            className="flex items-center gap-2 font-space-grotesk text-sm font-semibold"
            aria-label="Arcora home"
          >
            <Icon icon="solar:stars-minimalistic-linear" className="text-[#D97757]" width={18} />
            Arcora
          </Link>
          <Link
            href="/signup"
            className="bg-[#D97757] hover:bg-[#C26242] text-white text-xs font-semibold px-4 py-2 rounded-full font-space-grotesk transition-colors"
          >
            Generate yours →
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <p className="font-space-grotesk text-xs uppercase tracking-[0.6px] text-[#D97757] mb-2">
          Sample plan
        </p>
        <h1 className="font-instrument-serif text-3xl sm:text-5xl leading-[1.1] mb-3">
          A {found.label}&apos;s
          <br className="hidden sm:block" /> first 90 days, generated by AI.
        </h1>
        <p className="font-space-grotesk text-base text-[#57534E] mb-8 max-w-prose">
          This is a sample of what Arcora produces — pre-generated, not personalised
          to you. Your real plan is built around your role, company, manager,
          team shape, and goals in about a minute.
        </p>

        {/* Role switcher */}
        <div className="mb-10 flex flex-wrap gap-2">
          {SAMPLE_ROLES.map((r) => {
            const isActive = r.slug === found.slug;
            return (
              <Link
                key={r.slug}
                href={`/sample/${r.slug}`}
                className={`text-xs px-3 py-1.5 rounded-full border font-space-grotesk transition-colors ${
                  isActive
                    ? "bg-[#1C1917] text-white border-[#1C1917]"
                    : "bg-white text-[#57534E] border-[#E7E5E4] hover:border-[#1C1917]"
                }`}
              >
                {r.label}
              </Link>
            );
          })}
        </div>

        <PlanReadOnlyView
          plan={found.plan}
          ctaHref="/signup"
          ctaLabel="Generate your real plan in 5 minutes →"
          showAttribution={false}
        />

        <hr className="my-12 border-[#E7E5E4]" />

        <section className="text-center">
          <h2 className="font-instrument-serif text-2xl sm:text-3xl mb-3">
            Yours will be more specific than this.
          </h2>
          <p className="font-space-grotesk text-sm text-[#57534E] mb-6 max-w-xl mx-auto">
            Arcora reads your role context — title, company stage, team
            structure, manager, your own definition of success — and tailors the
            plan to that. The sample is a starting point; your plan is the real
            thing.
          </p>
          <Link
            href="/signup"
            className="inline-flex items-center gap-2 bg-[#D97757] hover:bg-[#C26242] text-white font-semibold px-6 py-3 rounded-full font-space-grotesk text-sm transition-colors shadow-sm"
          >
            Generate your real plan
          </Link>
        </section>
      </main>

      <footer className="mt-16 border-t border-[#D1CDC7] py-6">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row justify-between items-center gap-3 text-xs text-[#78716C] font-space-grotesk">
          <p>© {new Date().getFullYear()} Rulz &amp; Co · Arcora</p>
          <div className="flex gap-5">
            <Link href="/" className="hover:text-[#D97757]">Home</Link>
            <Link href="/terms" className="hover:text-[#D97757]">Terms</Link>
            <Link href="/privacy" className="hover:text-[#D97757]">Privacy</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
