// Curated sample plans rendered at /sample/[role].
//
// These are NOT live AI generations. Each one was hand-tuned from a real
// AI output so the marketing pages stay fast (no spinner, no API spend),
// the demo content stays high-quality, and we don't risk a bad generation
// embarrassing us on a public surface that strangers see first.
//
// Refresh cadence: re-curate quarterly, or whenever the prompt changes
// materially. The shape matches the sanitized plan contract documented at
// the top of src/components/plan/PlanReadOnlyView.js.

import productManager from "./product-manager.json";
import softwareEngineer from "./software-engineer.json";
import designer from "./designer.json";
import salesAe from "./sales-ae.json";

export const SAMPLE_ROLES = [
  {
    slug: "product-manager",
    label: "Senior Product Manager",
    seoTitle: "What a Senior Product Manager's first 90 days looks like — Arcora sample",
    seoDescription:
      "A real-world sample of an AI-generated 90-day plan for a Senior Product Manager. Phases, goals, milestones, and a week 1 preview.",
    plan: productManager,
  },
  {
    slug: "software-engineer",
    label: "Senior Software Engineer",
    seoTitle: "What a Senior Software Engineer's first 90 days looks like — Arcora sample",
    seoDescription:
      "Sample 30/60/90-day onboarding plan for a Senior Software Engineer joining a new team — generated by Arcora.",
    plan: softwareEngineer,
  },
  {
    slug: "designer",
    label: "Staff Product Designer",
    seoTitle: "What a Staff Product Designer's first 90 days looks like — Arcora sample",
    seoDescription:
      "Sample 30/60/90-day onboarding plan for a Staff Product Designer leading a new product surface — generated by Arcora.",
    plan: designer,
  },
  {
    slug: "sales-ae",
    label: "Sales Account Executive",
    seoTitle: "What an Account Executive's first 90 days looks like — Arcora sample",
    seoDescription:
      "Sample 30/60/90-day onboarding plan for a B2B SaaS Account Executive — generated by Arcora.",
    plan: salesAe,
  },
];

export function getSampleRole(slug) {
  return SAMPLE_ROLES.find((r) => r.slug === slug) || null;
}
