import Link from "next/link";
import { notFound } from "next/navigation";
import { Icon } from "@iconify/react";
import { ConvexHttpClient } from "convex/browser";
import { api } from "../../../../convex/_generated/api";
import PlanReadOnlyView from "@/components/plan/PlanReadOnlyView";

// Public read-only viewer for an opt-in shared plan.
// Server component — Convex query runs server-side via ConvexHttpClient
// to fetch the sanitized plan shape. No auth required.
//
// Privacy posture:
//   - getByPublicSlug returns null if the user has toggled sharing off,
//     so a stale slug 404s correctly.
//   - We force noindex via metadata.robots so user-public plans don't
//     leak into Google by default. SEO of *user* plans is a deliberate
//     post-launch decision.

const CONVEX_URL =
  process.env.NEXT_PUBLIC_CONVEX_URL ?? process.env.CONVEX_SITE_URL;

export const revalidate = 60; // light edge cache; toggling off invalidates implicitly via 404

async function fetchPublicPlan(slug) {
  if (!CONVEX_URL) return null;
  const client = new ConvexHttpClient(CONVEX_URL);
  try {
    return await client.query(api.publicPlans.getByPublicSlug, { slug });
  } catch {
    return null;
  }
}

export async function generateMetadata({ params }) {
  const { slug } = await params;
  const plan = await fetchPublicPlan(slug);
  if (!plan) {
    return {
      title: "Plan not found",
      robots: { index: false, follow: false },
    };
  }
  const title = plan.roleTitle
    ? `${plan.displayName}'s 90-day plan as ${plan.roleTitle} \u00b7 Arcora`
    : `${plan.displayName}'s 90-day plan \u00b7 Arcora`;
  const description = plan.successDefinition
    ? plan.successDefinition.slice(0, 200)
    : "A read-only view of an Arcora 90-day onboarding plan.";

  return {
    title,
    description,
    // Public plans are not indexed by default. The sample marketing pages
    // are the SEO surface; user plans are private content the user
    // chose to make link-shareable.
    robots: { index: false, follow: false },
    openGraph: {
      title,
      description,
      type: "article",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

export default async function PublicPlanPage({ params }) {
  const { slug } = await params;
  const plan = await fetchPublicPlan(slug);
  if (!plan) notFound();

  return (
    <div className="min-h-screen bg-[#F5F2E8] text-[#1C1917]">
      <header className="border-b border-[#D1CDC7] bg-[#F5F2E8]/95 sticky top-0 z-30 backdrop-blur">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
          <Link
            href="/"
            className="flex items-center gap-2 font-space-grotesk text-sm font-semibold"
            aria-label="Arcora home"
          >
            <Icon icon="solar:stars-minimalistic-linear" className="text-[#D97757]" width={18} />
            Arcora
          </Link>
          <Link
            href="/signup"
            className="bg-[#D97757] hover:bg-[#C26242] text-white text-xs font-semibold px-4 py-2 rounded-full font-space-grotesk transition-colors"
          >
            Generate yours →
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <p className="font-space-grotesk text-xs uppercase tracking-[0.6px] text-[#D97757] mb-2">
          Shared plan
        </p>
        <h1 className="font-instrument-serif text-3xl sm:text-5xl leading-[1.1] mb-3">
          {plan.displayName}&apos;s first 90 days.
        </h1>
        <p className="font-space-grotesk text-base text-[#57534E] mb-8 max-w-prose">
          A read-only view of {plan.displayName}&apos;s onboarding plan,
          generated by Arcora. Names, journal entries, and notes are kept
          private.
        </p>

        <PlanReadOnlyView plan={plan} ctaHref="/signup" />
      </main>

      <footer className="mt-16 border-t border-[#D1CDC7] py-6">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row justify-between items-center gap-3 text-xs text-[#78716C] font-space-grotesk">
          <p>© {new Date().getFullYear()} Rulz &amp; Co · Arcora</p>
          <div className="flex gap-5">
            <Link href="/" className="hover:text-[#D97757]">Home</Link>
            <Link href="/terms" className="hover:text-[#D97757]">Terms</Link>
            <Link href="/privacy" className="hover:text-[#D97757]">Privacy</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
